name: Setup Sui CLI
description: Install Sui CLI and add it to PATH.
runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      run: |
        if ! command -v rustup >/dev/null 2>&1; then
          curl -sSfL https://sh.rustup.rs | sh -s -- -y
        fi
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
        if [ "${SUI_CLI_CHANNEL:-}" = "nightly" ] || [ "${SUI_CLI_NIGHTLY:-}" = "1" ]; then
          rustup toolchain install nightly
        fi
      shell: bash

    - name: Install Sui CLI
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SUI_CLI_USE_SUIUP: "1"
      run: |
        node scripts/ci/install-sui-cli.mjs
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      shell: bash
