name: Setup workspace
description: Checkout repo, install pnpm, configure Node, and install dependencies.
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - run: pnpm install --frozen-lockfile
      shell: bash
