import {
  DEFAULT_PUBLISH_GAS_BUDGET,
  DEFAULT_TX_GAS_BUDGET,
  MINIMUM_ACCOUNT_BALANCE,
  MINIMUM_GAS_COIN_BALANCE,
  MINIMUM_GAS_COIN_OBJECTS,
  NORMALIZED_SUI_COIN_TYPE,
  ONE_SUI,
  SUI_COIN_TYPE,
  SUI_CLOCK_ID,
  SUI_COIN_REGISTRY_ID
} from "@sui-oracle-market/tooling-core/constants"
import os from "node:os"
import path from "node:path"

export const DEFAULT_KEYSTORE_PATH = path.join(
  os.homedir(),
  ".sui",
  "sui_config",
  "sui.keystore"
)

export {
  DEFAULT_PUBLISH_GAS_BUDGET,
  DEFAULT_TX_GAS_BUDGET,
  MINIMUM_ACCOUNT_BALANCE,
  MINIMUM_GAS_COIN_BALANCE,
  MINIMUM_GAS_COIN_OBJECTS,
  NORMALIZED_SUI_COIN_TYPE,
  ONE_SUI,
  SUI_COIN_TYPE,
  SUI_CLOCK_ID,
  SUI_COIN_REGISTRY_ID
}
